version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fiber
    restart: 'always'
    env_file:
      - .env
    network_mode: 
      host
    volumes:
      - ./src:/app/src
    command: go run main.go --host=0.0.0.0